# Generated by Django 3.1 on 2020-08-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20200814_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images_topics/', verbose_name='Image'),
        ),
    ]
