# Generated by Django 3.1 on 2020-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20200814_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images_topics/', verbose_name='Image'),
        ),
    ]
